import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // toolsetSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  toolsetSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Developer Tools',
      items: ['document-generator/introduction'

      ],
    },
    {
      type: 'category',
      label: 'Model-driven Apps',
      items: [{
        type: 'category',
        label: 'Template Engine',
        items: [
          'template-engine/introduction',
          'template-engine/expressions',
          {
            type: 'category',
            label: 'Use Cases',
            items: [
              'template-engine/use-cases/phonecall-activities-onbooking-creation',
              'template-engine/use-cases/lead-retention-period',
              'template-engine/use-cases/api-trigger',
            ],
          },
          'template-engine/limitations'
        ],
      }
      ],
    },
  ],
};

export default sidebars;
